name: Close and lock inactive threads
on:
  schedule:
    - cron: "0 8 * * *"

permissions:
  contents: read

jobs:
  manage-inactive:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@5bef64f19d7facfb25b37b414482c7164d639639 # v9
        with:
          days-before-issue-stale: 45
          days-before-issue-close: 30
          stale-issue-label: inactive
          stale-issue-message: >
            This issue has been automatically marked as inactive 
            due to lack of recent activity. 
            Should you believe it remains unresolved and warrants attention, 
            kindly leave a comment on this thread. 
          exempt-issue-labels: enhancement,discussion
          days-before-pr-stale: -1
          days-before-pr-close: -1
          operations-per-run: 128
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: dessant/lock-threads@1bf7ec25051fe7c00bdd17e6a7cf3d7bfb7dc771 # v5
        with:
          issue-inactive-days: 60
          issue-comment: >
            This issue has been automatically locked since there
            has not been any recent activity after it was closed.
            Please open a new issue for related bugs.
          pr-inactive-days: 90
          pr-comment: >
            This pull request has been automatically locked since there
            has not been any recent activity after it was closed.
            Please open a new issue for related bugs.
          repo-token: ${{ secrets.GITHUB_TOKEN }}
